### ISSUE TITLE
custom logger format output

### ISSUE THREAD

**Issue by derit** [google/logger#17]
output by default

> INFO : 2018/09/26 06:00:06.607994 test.go:25: hello

how to remove date info and  test.go:25 just need "hello"

**Comment by cixtor** [comment]
I have implemented this with [pull-request 18](https://github.com/google/logger/pull/18) .

Once merged, you’ll be able to add `logger.SetFlags(log.LUTC)` after the init.

**Note:** As long as you don’t set `Ldate` nor `Ltime`, only the message will be written.
