### ISSUE TITLE
undefined: setup

### ISSUE THREAD

**Issue by mike-seagull** [google/logger#21]
Getting:
<code>google/logger/logger.go:81:21: undefined: setup</code>
when running <code>go get github.com/google/logger</code>

go version go1.11.4 linux/amd64

**Comment by adjackura** [comment]
That function is os specific, for linux/darwin its in logger/logger_syslog.go, is your GOOS set to anything other than linux?

**Comment by mike-seagull** [comment]
yes <code>GOOS=freebsd GOARCH=amd64</code>

**Comment by adjackura** [comment]
Ah, so this is untested on freebsd but if the syslog setup works on freebsd as well (simply add it to the +build statement) feel free to send a PR.

**Comment by mike-seagull** [comment]
Sounds good. The syslog setup does work for freebsd. Is there a test suite that I can run prior to submitting the pull request?

**Comment by adjackura** [comment]
We don't have any tests for the systemlog access as that is very os dependent. Just ensure that it compiles and actually logs to syslog on freebsd.
